writer.writerow({'id': id_v4,
                                         'screen_name': row_v4['screen_name'],
                                         'age': row_v4['age'],
                                         'in_out_ratio': row_v4['in_out_ratio'],
                                         'favorites_ratio': row_v4['favorites_ratio'],
                                         'status_ratio': row_v4['status_ratio'],
                                         'account_rep': row_v4['account_rep'],
                                         'avg_tpd': row_v4['avg_tpd'],
                                         'hashtags_ratio': row_v4['hashtags_ratio'],
                                         'user_mentions_ratio': row_v4['user_mentions_ratio'],
                                         'url_ratio': row_v4['url_ratio'],
                                         'cce': row_v3['cce'],
                                         'spam_ratio': row_v3['spam_ratio'],
                                         'avg_cosine_similarity': row_v4['avg_cosine_similarity'],
                                         'avg_tweet_sentiment': row_v4['avg_tweet_sentiment'],
                                         'std_deviation_friends': row_v4['std_deviation_friends'],
                                         'std_deviation_followers': row_v4['std_deviation_followers'],
                                         'unique_urls_ratio': row_v4['unique_urls_ratio'],
                                         'tweet_url_similarity': row_v4['tweet_url_similarity'],
                                         'user_description_len': row_v4['user_description_len'],
                                         'user_description_sentiment': row_v4['user_description_sentiment'],
                                         'special_char_in_description': row_v4['special_char_in_description'],
                                         'tweet_count': row_v4['tweet_count'],
                                         'description': row_v3['description'],
                                         'bot': row_v3['bot']})



features = ['id',
                    'screen_name',
                    'age',
                    'in_out_ratio',
                    'favorites_ratio',
                    'status_ratio',
                    'account_rep',
                    'avg_tpd',
                    'hashtags_ratio',
                    'user_mentions_ratio',
                    'url_ratio',
                    'cce',
                    'spam_ratio',
                    'avg_cosine_similarity',
                    'avg_tweet_sentiment',
                    'std_deviation_friends',
                    'std_deviation_followers',
                    'unique_urls_ratio',
                    'tweet_url_similarity',
                    'user_description_len',
                    'user_description_sentiment',
                    'special_char_in_description',
                    'tweet_count',
                    'description',
                    'bot']